{% set name = "issho" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e994a9c91249152d9f36f9b5e76fe264daebda038a9702b8972224acaa40928d 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - issho = issho.cli:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - keyring
    - paramiko
    - toml
    - fire
    - humanize
    - prompt_toolkit
    - sshtunnel

test:
  imports:
    - issho

about:
  home: http://github.com/michaelbilow/issho
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: simple access to commands on a remote machine over ssh

  description: |
    issho is an intuitive wrapper over paramiko for configuring and talking to a remote host. 
    keyring is used to manage secrets locally.
    issho is designed such that interacting with a single, heavily used remote machine 
    should be easy, and working with more than one remote machine should be simple.
  doc_url: http://issho.readthedocs.io/
  dev_url: https://github.com/michaelbilow/issho

extra:
  recipe-maintainers:
    - michaelbilow
